# Generated by Django 3.0.7 on 2020-06-17 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(related_name='following_someone', to=settings.AUTH_USER_MODEL),
        ),
    ]
